### ISSUE TITLE
Add test cases using vanilla javascript

### ISSUE THREAD

**Issue by bhatvikrant** [bhatvikrant/world-countries-capitals#1]

**Comment by Levi-Thieme** [comment]
It might be a good idea to consider using Jasmine with Karma in order to automate executing all of the tests.
https://jasmine.github.io/
https://karma-runner.github.io/latest/index.html

I would be willing to set it up for the project.

**Comment by bhatvikrant** [comment]
That would be great man @Levi-Thieme . Please confirm that you will take on this task and I will assign it to you then 😄

**Comment by Levi-Thieme** [comment]
Yes, I will take it on. I have also left a comment on the issue about getting countries by famous things. Can you assign that to me as well?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bhatvikrant** [comment]
Cool assigned issue #1 to you .

 Will reply there only for that issue.😇
