### ISSUE TITLE
Enhance the README.md file i.e. the documentation 

### ISSUE THREAD

**Issue by bhatvikrant** [bhatvikrant/world-countries-capitals#10]

**Comment by Levi-Thieme** [comment]
Suggestion: A good thing to include in the README file under the contributors section would be how to execute the tests(npm test). This would prevent contributors from contributing and breaking the tests with their contributions due to not knowing about them or how to execute them.

**Comment by bhatvikrant** [comment]
Okay , I will add it in the next release.

**Comment by bhatvikrant** [comment]
@Levi-Thieme would you like to be a *Collaborator* in this repository? Your inputs have really helped and will be valuable in the future also.😀

**Comment by Levi-Thieme** [comment]
Yes, that would be great. Thank you!

**Comment by sudo-kaizen** [comment]
Has this issue been resolved?

**Comment by bhatvikrant** [comment]
@sudo-kaizen no this is still pending. You can pick it up, if you like.

**Comment by debugleader** [comment]
Hey, are you still online? @bhatvikrant

**Comment by bhatvikrant** [comment]
Hey there @debugleader, yup I am here.

**Comment by debugleader** [comment]
Please check my PR @bhatvikrant

**Comment by bhatvikrant** [comment]
@debugleader I ll review your PR on the weekend. Thanks for the contribution!

**Comment by debugleader** [comment]
Welcome :wink: Always happy to help!
Please contact me in the future if you need anything. @bhatvikrant

**Comment by damn-dvlpr** [comment]
Hey @bhatvikrant can you please throw some light upon what needs to be enhanced in documentation more elaborately?

**Comment by bhatvikrant** [comment]
> Hey @bhatvikrant can you please throw some light upon what needs to be enhanced in documentation more elaborately?

Yes sure.

- You can create a working example (Demo) utilizing the library (codesandbox/ online code sharing platforms are suggested). It could be in Gatsby/Vue/React/ any JS library or framework. This is just to increase working examples.

- You can also restructure the existing documentation in a better way if you feel that way or add any missing data into the documentation.

- Discuss any other ideas you have, I am always open to new ideas!

**Comment by damn-dvlpr** [comment]
@bhatvikrant I have implemented a new API and added its documentation too, also the readme was missing information about this new property "drive_direction", i have added those too. #57
