### ISSUE TITLE
Create a function in index.js to show countries by what they are famous for

### ISSUE THREAD

**Issue by bhatvikrant** [bhatvikrant/world-countries-capitals#16]

**Comment by Levi-Thieme** [comment]
I have implemented this function with a test. Can you please add me to the repo, so I can create a PR?

**Comment by bhatvikrant** [comment]
Assigned this issue to you. Please Fork the repository to Raise a PR. 
Also , it would really help me to reach more devs if you could star the repository.😇

**Comment by Levi-Thieme** [comment]
Got it. I figured out that I need to fork it earlier, and have done so. There is a PR up for this right now.

**Comment by bhatvikrant** [comment]
Great! and that was fast! 😁 , I ll review the PR in a bit @Levi-Thieme .
