### ISSUE TITLE
Add more data in data.json

### ISSUE THREAD

**Issue by bhatvikrant** [bhatvikrant/world-countries-capitals#2]
Add more data in data/data.json.
Add fields like GDP, population, Global rank, etc.

Guidelines:
-  GDP should be USD million

- population number should be in million

                    
data.json format: 
for eg. 
```
{
        "country": "Afghanistan",
        "capital": "Kabul",
        "currency": "Afghani",
        "native_language": "Dari Persian, Pashto",
        "GDP": 19,630,
        "population": 39.20 
        "global_rank": 78
}
```

**Comment by yatharth17** [comment]
Can i contribute?

**Comment by bhatvikrant** [comment]
Yes absolutely @yatharth17 !  Make some useful changes and raise a PR!  Would be awesome if you contribute.

**Comment by yatharth17** [comment]
@bhatvikrant Can you tell me on what basis i need to update the country global rank?As in there are various rankings based on different parameters.

**Comment by bhatvikrant** [comment]
The basis of ranking a country can be the overall of various fields.
[check this](https://media.beam.usnews.com/55/57/eb2338c7493eadf38e29db4b8dca/190116-best-countries-overall-rankings-2019.pdf)

You can find various lists on google like the above link. The above link does not have all the countries listed, you must search for a list that has all the countries that are in our data.json.
