### ISSUE TITLE
Add unique data to src/data.json 

### ISSUE THREAD

**Issue by bhatvikrant** [bhatvikrant/world-countries-capitals#23]

**Comment by sanilborkar** [comment]
Could you please elaborate? What unique data are we talking about?

**Comment by pswartz66** [comment]
Not exactly sure what you mean by unique data but if you mean add another property to each object below is a function that you could use to easily add data into the json data. I just required it in as jsonObj for testing purposes. Hope this helps! 

const jsonObj = require('./clonedJSON');

function addUniqueData(arr) {
    // loop through the jsonObj
    for (let i = 0; i < arr.length; i++) {
        // add unique data to each country object
        arr[i].uniqueData = i + 'xyz';
    }
    return arr;
}

console.log(addUniqueData(jsonObj));

**Comment by bhatvikrant** [comment]
@sanilborkar as @pswartz66 rightly prompted, by unique data I mean , data that is unique to every country and it doesn't changes with time. for example: Land area, capital etc.. a wrong example would be population (since it changes with time, its variable)

**Comment by bhatvikrant** [comment]
Thanks @pswartz66 ! I' ll definitely use this helper function! Appreciat it!

**Comment by sudo-kaizen** [comment]
@bhatvikrant 
1. Does year of independence suffice for unique data?
2. If it does, what will the value be for countries without an independence date like England?

**Comment by bhatvikrant** [comment]
@sudo-kaizen yes, this will be considered as unique data. For countries like England just add the string : 'N/A'

**Comment by faraz16iqbal** [comment]
Is this issue still open?

**Comment by bhatvikrant** [comment]
@faraz16iqbal yes it is.

**Comment by ccsCoder** [comment]
Would you consider popular tourist attractions as Unique ? E.g

```javascript
France: ['Eiffel Tower'],
India: ['Taj Mahal', 'Qutub Minar'],
```

**Comment by bhatvikrant** [comment]
@ccsCoder yea sounds good

**Comment by Ac-Srikanth** [comment]
Hi @bhatvikrant , i have modified the famous for fields in the data for the following countries , syria, turkey, austria and sweden. Do check .

**Comment by vijaykrishna536** [comment]
Hi @bhatvikrant, Added a unique property timezone to data.json #64  
Please review. Thank you

**Comment by sthiepaan** [comment]
Since we have #32 _Issue_ opened, there is no reason for having this one as well. So for now **lets stick to one issue opened**.

On the other hand, I think we should have separate _Issues_ created for each bug/feature, so the discussion is clear.
