### ISSUE TITLE
drive_direction field in data should have only 'right' or 'left' as value

### ISSUE THREAD

**Issue by amanpalariya** [bhatvikrant/world-countries-capitals#35]
I think the the `drive_direction` field should have value either `right` or `left`. Currently, it says `drives on the right` or `drives on the left`.

**Comment by bhatvikrant** [comment]
@amanpalariya it's a good suggestion,  I agree with your point of view. 

Anyone who is interested shall take up this task. I ll assign it to them. Just let me know 😄

**Comment by amanpalariya** [comment]
I wish to take up this task. 😀

Please confirm if the following is what I am supposed to do.
- Make changes in `data/data.json`
- Clone `data/data.json` to `data/tests/clonedJSON.json`
- Run `data/tests/test.js`

**Comment by bhatvikrant** [comment]
@amanpalariya sounds good. Assigning this to you.
