### ISSUE TITLE
Adding area field to data

### ISSUE THREAD

**Issue by amanpalariya** [bhatvikrant/world-countries-capitals#40]
The `area` is one of the very important stats for a country. So, it should be added to the data.

@bhatvikrant What should be the unit of area? I think **km<sup>2</sup>** would be the best.

So, the schema will be

```
{
    "country": <country-name>
    ...
    "area": <area-in-sq-km>
}
```
Should we mention the unit in the data? 🤔

I guess it would be best to store `area` as a `double` and mention the unit in documentation only.

**Comment by bhatvikrant** [comment]
Yea, even I think  **km<sup>2</sup>** is the best option for the unit, it's widely used.

Don't mention the unit in the `area` key, instead make another key `area_unit` and put its value as **km<sup>2</sup>**.

what do you think? I'm open to suggestions @amanpalariya

**Comment by amanpalariya** [comment]
I was thinking of **not mentioning** the unit in the data at all and just keep it limited to the documentation.

If we include `area_unit`, it will make the user think that some countries may have data in other units too.

**Comment by bhatvikrant** [comment]
Hmm, interesting thought. @amanpalariya 

I think we can tackle it by structuring the area schema as follows: 

```js
  ...
  "area": {
        value: 10000,
        unit: "Km^2"            
   }
  ...
```

**Comment by sthiepaan** [comment]
If we don't want to deliver _area unit_ then as @amanpalariya mentioned, we might use _JSDocs_ (for methods) and `README.md` Documentation for that information.

> If we include `area_unit`, it will make the user think that some countries may have data in other units too.

That actually could be a thing if we want to deliver _english units_ such as _square miles_. The question is, do we want to deliver that for a users or should they calculate it by themselves?

**Comment by amanpalariya** [comment]
@sthiepaan Nice idea! 👍

This way, the area is provided in two major units.

But, if done this way, we will have to maintain consistency in `data.json` itself (can be done with the help tests only).

Extending @sthiepaan's idea, we can store area in km<sup>2</sup> in `data.json` but while returning, we can convert the data into mi<sup>2</sup> also and return what @sthiepaan proposed.

So, `data.json` contains
```js
{
  //...,
  "area": 312769
}
```

But the method returns 👇
```js
{
  //...,
  "area": {
    "km2": 312679,
    "mi2": 120726,
  }
}
```

**Comment by sthiepaan** [comment]
From my point of view, _API_ should just return the date that it contain. Even if we have methods to grab specific data, we do not modify the output. If we create some functionality to convert the data, then we need to take care at least for _correctness of calculated data_ and _units rounding_.

I would leave calculations for _API consumers_ so they can decide what format they want to have. So just to summarize I think there are two proper ways:
- Deliver data only in one format and let user play with that (I'd suggest using _SI_ unit meter ➡️ `square meter`)
- Deliver mostly used units so users can just grab it for the _API_ (so _at least_ two _areas units_ ➡️ `km2` and `mi2`)

**Comment by bhatvikrant** [comment]
Yeah, @sthiepaan  I agree. I think the unit conversions should be left to the consumer itself. Let's proceed with this

**Comment by amanpalariya** [comment]
Since, we are going for 
{
  //...,
  "area": {
    "km2": 312679,
    "mi2": 120726,
  }
}
