### ISSUE TITLE
Add new API Property - neighbors

### ISSUE THREAD

**Issue by sthiepaan** [bhatvikrant/world-countries-capitals#46]
After short introduction in #32 we decided to extend this package with `neighbors` Property:
- `neighbors` Property is a `string[]` (list of strings)
- Each value in that property is a value taken from `iso.alpha_2` of a country
- The values should be ordered **alphabetically**
- For the project needs all new properties will be **lowercase**.

After adding new property, each Country {Object} should contain:
```js
{
  "country": "poland",
  "capital": "warsaw",
  "currency": "zloty",
  "native_language": ["polish"],
  "famous_for": "pierogi and potatoes",
  "phone_code": "+48",
  "flag": "https://flagpedia.net/data/flags/h80/pl.png",
  "drive_direction": "right",
  "iso": {
    "numeric": "616",
    "alpha_2": "pl",
    "alpha_3": "pol"
  },
  // NEW DATA
  "neighbors": ["by", "cz", "de", "lt", "ru", "sk", "ua"]
},
```

Additionally there will be new method to use that data:
- `getCountryNeighbors(countryName)`

**NOTE**: This feature is dependant on #42 so it has to be merged before preparing this

**Comment by sthiepaan** [comment]
@bhatvikrant since this is connected with #42 and I am working on this let me take care of that one 😉

**Comment by bhatvikrant** [comment]
Okay @sthiepaan I will assign this one to you too.

**Comment by sthiepaan** [comment]
@bhatvikrant when will you have time to do the _code review_ for #42 _Pull Request_? As I mentioned earlier, this one is dependent on it 😉
