### ISSUE TITLE
 Add new API Property - is_landlocked

### ISSUE THREAD

**Issue by sthiepaan** [bhatvikrant/world-countries-capitals#47]
After short introduction in #32 we decided to extend this package with `is_landlocked` Property:
- `is_landlocked` Property is a `Boolean`

After adding new property, each Country {Object} should contain:
```js
{
  "country": "poland",
  "capital": "warsaw",
  "currency": "zloty",
  "native_language": ["polish"],
  "famous_for": "pierogi and potatoes",
  "phone_code": "+48",
  "flag": "https://flagpedia.net/data/flags/h80/pl.png",
  "drive_direction": "right",
  // NEW DATA
  "is_landlocked": false
},
```

Additionally there will be new method to use that data:
- `getCountriesByLandlock(isLandLocked)`

**Comment by jav7zaid** [comment]
@bhatvikrant can you assign this to me? I think this would be good first issue and contribution ? Thanks 👍

**Comment by bhatvikrant** [comment]
@jav7zaid Sure thing! I have assigned this issue to you. 
All the best! 
Also, please don't forget to mention your source of data in the PR.😀

**Comment by jav7zaid** [comment]
@bhatvikrant thanks! 😄

**Comment by jav7zaid** [comment]
@sthiepaan can you please open this PR , i need to fix the existing test cases that broke.

**Comment by sthiepaan** [comment]
Sure 👍 Please make a new _Pull Request_ with fix for that _ASAP_.
