### ISSUE TITLE
 Add new API Property - minimum_driving_age

### ISSUE THREAD

**Issue by sthiepaan** [bhatvikrant/world-countries-capitals#49]
After short introduction in #32 we decided to extend this package with `minimum_driving_age` Property:
- `minimum_driving_age` Property is a `Number` that represents minimum age to drive a car

After adding new property, each Country {Object} should contain:
```js
{
  "country": "poland",
  "capital": "warsaw",
  "currency": "zloty",
  "native_language": ["polish"],
  "famous_for": "pierogi and potatoes",
  "phone_code": "+48",
  "flag": "https://flagpedia.net/data/flags/h80/pl.png",
  "drive_direction": "right",
  // NEW DATA
  "minimum_driving_age": 18
},
```

Additionally there will be new method to use that data:
- `getCountriesByMinimumDrivingAge(minimumAge, isExact)`

**Comment by bhatvikrant** [comment]
@sthiepaan I am not sure about this property. I feel it's not that common/useful. (Please feel free to contest me by all means)

Let's keep this low priority for now.

**Comment by sthiepaan** [comment]
It came to my mind because we have `drive_direction` Property 😛

I checked what are the values for countries and it looks like there are not much _"unexpected"_ values that we would like to share. Mostly it is a range between 15 and 20 where most of the countries have 18 as a minimum driving age.

So for now I will close this ticket and we can reopen it if we are back to this topic.
Thanks for an input @bhatvikrant ✌️
