### ISSUE TITLE
 Add new API Property - constitutional_form

### ISSUE THREAD

**Issue by sthiepaan** [bhatvikrant/world-countries-capitals#51]
After short introduction in #32 we decided to extend this package with `constitutional_form` Property:
- `constitutional_form` Property is a one of `String`
- Accepted values: "republic", "constitutional monarchy", "absolute monarchy" or "n/a"
- For the project needs all new properties will be **lowercase**

After adding new property, each Country {Object} should contain:
```js
{
  "country": "poland",
  "capital": "warsaw",
  "currency": "zloty",
  "native_language": ["polish"],
  "famous_for": "pierogi and potatoes",
  "phone_code": "+48",
  "flag": "https://flagpedia.net/data/flags/h80/pl.png",
  "drive_direction": "right",
  // NEW DATA
  "constitutional_form": "republic"
},
```

Additionally there will be new method to use that data:
- `getCountriesByConstitutionalForm(constitutionalFormName)`

**Comment by sthiepaan** [comment]
If there are no additional inputs, let me handle this @bhatvikrant 🚀

**Comment by bhatvikrant** [comment]
@sthiepaan your proposal looks great. Go ahead with it bud 💪🏻.
