### ISSUE TITLE
Add new API Property - TimeZone

### ISSUE THREAD

**Issue by jav7zaid** [bhatvikrant/world-countries-capitals#53]
Hi Guys 👋 ,

how often have we search to find out timezone for a country/city to get the current time 😉. 
Lets add a functionality for the user, to fetch the time zone for the country given as input, in our case it will be the **capital city** time zone.

As mentioned in issue [#32](https://github.com/bhatvikrant/world-countries-capitals/issues/32) to extend the package with new features, i would like to propose to add `TimeZone` Property 👍 

- TimeZone would be string and in GMT/UTC format.
- We can either take **Country or Capital ** as input.

```
{
    "country": "afghanistan",
    "capital": "kabul",
    "currency": "afghani",
    "native_language": ["dari persian", "pashto"],
    "famous_for": "rugs, taliban",
    "phone_code": "+93",
    "flag": "https://flagpedia.net/data/flags/h80/af.png",
    "drive_direction": "right",
    **"timeZone": "GMT+4:30"** // new field
  },
```

There will be new method `getCountryTimeZone(countryName/capitalName)` to get the below data,

```
[
    {
      "timeZone": "GMT+4:30",
      "timeNow": "Oct 04 2020 10:20:00" // will give the current time
    }
]
```

Let me know guys ! 😄

**Comment by sthiepaan** [comment]
I am not sure about having this. It would be limited and so hard to use. For example in _Russia_ there are **11** timezones(!) And this is just one case which is making my mind blown 🤯🤯🤯 😅...
But from more technical point of view we already have that in _JavaScript_ using [Intl.DateTimeFormat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) Object.

What we could actually do is deliver [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) _language codes_ to each country so _API consumers_ may use it to format their data using specific country format.

**Comment by jav7zaid** [comment]
@sthiepaan I get your point lot of countries have more than one time zone, but what about capturing for just the capital city ? It would be fine right.

**Comment by sthiepaan** [comment]
@jav7zaid you can achieve the same using _JavaScript_:
```js
const options = {
  day: '2-digit',
  month: '2-digit',
  year: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
  second: '2-digit',
  timeZone: 'Asia/Kabul', // Timezone set using formatted `continent` (delivered via #42 PR) and `capital`
  timeZoneName: 'short'
}
const formatter = new Intl.DateTimeFormat('pl-PL', options)
const startingDate = Date.now()
const dateInNewTimezone = formatter.format(startingDate) // output: "04.10.20, 13:56:19 GMT+4:30"
```

**Comment by sthiepaan** [comment]
We could deliver instead a `language_codes {string[]}` that would let _API consumers_ format their data with specific country format (could be used for _JS_ formatting or setting `lang` attribute for `<html>...</html>`). `language_codes` has to be an `Array` because there are countries that have multiple languages.

To solve that, we can use combination of _ISO 639-1_ and _ISO 3166-1 alpha-2_ codes (e.g.: `pl-PL`).
Sample `Country {Object}`:
```js
{
  "country": "poland",
  "capital": "warsaw",
  "currency": "zloty",
  "native_language": ["polish"],
  "famous_for": "pierogi and potatoes",
  "phone_code": "+48",
  "flag": "https://flagpedia.net/data/flags/h80/pl.png",
  "drive_direction": "right",
  // NEW DATA
  "language_codes": ["pl-PL"]
}
```

**Comment by bhatvikrant** [comment]
@jav7zaid I think @sthiepaan is right here. Timezone info can be extracted out.
